# Generated by Django 4.1 on 2022-08-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_rename_describetion_book_description_bookcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author", options={"verbose_name_plural": "Author"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created"], "verbose_name_plural": "Book"},
        ),
        migrations.AlterModelOptions(
            name="bookcomment",
            options={"ordering": ["id"], "verbose_name_plural": "Book Comment"},
        ),
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Category"},
        ),
        migrations.AddField(
            model_name="book",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("B", "Basic"), ("M", "Medium"), ("A", "Advanced")],
                max_length=5,
                null=True,
            ),
        ),
    ]
